import React, { useEffect, useMemo, useState } from 'react'
import { api } from './api.js'
import { translations } from './i18n.js'

const NAV = [['dashboard','◫'],['projects','▣'],['scanner','⌕'],['approvals','✓'],['policies','⚙'],['audit','≡'],['integration','⇄']]

function Badge({value,t}) {
  const tone = ['allow','approved'].includes(value) ? 'ok' : ['block','rejected','critical','high'].includes(value) ? 'danger' : ['approval','pending','medium'].includes(value) ? 'warn' : 'neutral'
  return <span className={'badge '+tone}>{t[value] || value}</span>
}

function Auth({lang,setLang,onAuth}) {
  const t=translations[lang], [mode,setMode]=useState('login'), [form,setForm]=useState({name:'',email:'',password:''}), [error,setError]=useState('')
  async function submit(e){e.preventDefault();setError('');try{const path='/api/auth/'+(mode==='login'?'login':'signup');const body=mode==='login'?{email:form.email,password:form.password}:{...form,language:lang};const d=await api(path,{method:'POST',body});onAuth(d.access_token,d.user)}catch(e){setError(e.message)}}
  return <div className="auth-shell"><button className="lang floating" onClick={()=>setLang(lang==='en'?'ar':'en')}>{t.language}</button><div className="auth-card"><div className="brand-mark">AG</div><h1>{t.appName}</h1><p>{t.tagline}</p><form onSubmit={submit}>{mode==='signup'&&<label>{t.name}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>{t.email}<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{t.password}<input type="password" minLength="8" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="alert danger-bg">{error}</div>}<button className="primary full">{mode==='login'?t.login:t.signup}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?t.noAccount:t.haveAccount}</button></div></div>
}

function ProjectSelect({token,t,value,onChange,includeAll=false}) {
  const [projects,setProjects]=useState([])
  useEffect(()=>{api('/api/projects',{token}).then(setProjects)},[token])
  return <select value={value ?? ''} onChange={e=>onChange(e.target.value?Number(e.target.value):null)}><option value="">{includeAll?t.all:t.chooseProject}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
}

function Dashboard({token,t}) {
  const [data,setData]=useState(null),[rows,setRows]=useState([]),[decision,setDecision]=useState(''),[source,setSource]=useState(''),[project,setProject]=useState(null)
  const load=()=>api('/api/dashboard',{token}).then(setData)
  const loadRows=()=>{const q=new URLSearchParams({limit:'100'});if(decision)q.set('decision',decision);if(source)q.set('source_type',source);if(project)q.set('project_id',project);api('/api/scans?'+q.toString(),{token}).then(setRows)}
  useEffect(()=>{load();loadRows()},[]);useEffect(()=>{loadRows()},[decision,source,project])
  async function exportCsv(){const base=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';const path='/api/reports/security.csv'+(project?'?project_id='+project:'');const r=await fetch(base+path,{headers:{Authorization:'Bearer '+token}});const b=await r.blob();const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='ai-agent-security-report.csv';a.click();URL.revokeObjectURL(u)}
  if(!data)return <div>{t.loading}</div>; const cards=[[t.totalScans,data.total_scans],[t.blocked,data.blocked],[t.allowed,data.allowed],[t.waiting,data.pending_approvals],[t.critical,data.critical]]
  return <><div className="page-head"><div><h2>{t.dashboard}</h2><p>{t.accountSecurity}</p></div><div className="actions"><button className="secondary" onClick={exportCsv}>{t.exportReport}</button><button className="secondary" onClick={()=>{load();loadRows()}}>{t.refresh}</button></div></div><div className="stats">{cards.map(([k,v])=><div className="stat" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><section className="panel"><div className="section-head"><h3>{t.recentActivity}</h3><div className="filters"><select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">{t.decision}: {t.all}</option><option value="allow">{t.allow}</option><option value="approval">{t.approval}</option><option value="block">{t.block}</option></select><select value={source} onChange={e=>setSource(e.target.value)}><option value="">{t.source}: {t.all}</option><option value="prompt">Prompt</option><option value="tool">Tool</option><option value="content">Content</option><option value="codex_prompt">Codex Prompt</option><option value="codex_tool">Codex Tool</option><option value="codex_tool_response">Codex Output</option></select><ProjectSelect token={token} t={t} value={project} onChange={setProject} includeAll/></div></div><table><thead><tr><th>{t.source}</th><th>{t.decision}</th><th>{t.risk}</th><th>{t.threat}</th><th>{t.date}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.source_type}</td><td><Badge value={x.decision} t={t}/></td><td>{x.risk_score}/100</td><td><Badge value={x.threat_level} t={t}/></td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></section></>
}

function Projects({token,t}) {
  const [rows,setRows]=useState([]),[form,setForm]=useState({name:'',description:''}),[error,setError]=useState('');const load=()=>api('/api/projects',{token}).then(setRows);useEffect(()=>{load()},[])
  async function create(e){e.preventDefault();setError('');try{await api('/api/projects',{method:'POST',token,body:form});setForm({name:'',description:''});load()}catch(e){setError(e.message)}}
  async function remove(id){await api('/api/projects/'+id,{method:'DELETE',token});load()}
  return <><div className="page-head"><h2>{t.projects}</h2></div><div className="split"><form className="panel" onSubmit={create}><h3>{t.createProject}</h3><label>{t.projectName}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t.description}<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{error&&<div className="alert danger-bg">{error}</div>}<button className="primary">{t.createProject}</button></form><div className="cards-list">{rows.length?rows.map(p=><div className="panel approval-card" key={p.id}><div><h3>{p.name}</h3><p>{p.description||'—'}</p></div><button className="danger-btn" onClick={()=>remove(p.id)}>{t.delete}</button></div>):<div className="panel empty">{t.noProjects}</div>}</div></div></>
}

function Scanner({token,t,lang}) {
  const [form,setForm]=useState({source_type:'prompt',source_text:'',tool_name:'',project_id:null}),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  async function run(e){e.preventDefault();setLoading(true);setError('');try{setResult(await api('/api/scans',{method:'POST',token,body:form}))}catch(e){setError(e.message)}finally{setLoading(false)}}
  return <><div className="page-head"><div><h2>{t.scanTitle}</h2><p>{t.scanHelp}</p></div></div><div className="split"><form className="panel" onSubmit={run}><label>{t.project}<ProjectSelect token={token} t={t} value={form.project_id} onChange={v=>setForm({...form,project_id:v})}/></label><label>{t.sourceType}<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})}><option value="prompt">{t.prompt}</option><option value="tool">{t.tool}</option><option value="content">{t.content}</option></select></label>{form.source_type==='tool'&&<label>{t.toolName}<input value={form.tool_name} onChange={e=>setForm({...form,tool_name:e.target.value})} placeholder="Bash / apply_patch / MCP tool"/></label>}<label>{t.text}<textarea rows="12" required value={form.source_text} onChange={e=>setForm({...form,source_text:e.target.value})} placeholder="Ignore previous instructions..."/></label>{error&&<div className="alert danger-bg">{error}</div>}<button className="primary">{loading?t.loading:t.analyze}</button></form><div className="panel result-panel">{result?<><div className="risk-ring" style={{'--risk':result.risk_score}}><strong>{result.risk_score}</strong><span>/100</span></div><div className="result-meta"><Badge value={result.decision} t={t}/><Badge value={result.threat_level} t={t}/></div><h3>{t.findings}</h3>{result.findings.length?result.findings.map((f,i)=><div className="finding" key={f.id+'-'+i}><div><b>{lang==='ar'?(f.title_ar||f.title):f.title}</b><small>{f.category+' · '+f.id}</small></div><Badge value={f.severity} t={t}/><p>{lang==='ar'?(f.recommendation_ar||f.recommendation):f.recommendation}</p></div>):<p>{t.noFindings}</p>}</>:<div className="empty">{t.findings}</div>}</div></div></>
}

function Approvals({token,t}) {
  const [data,setData]=useState([]),[status,setStatus]=useState(''); const load=()=>api('/api/approvals'+(status?'?status='+status:''),{token}).then(setData); useEffect(()=>{load();const id=setInterval(load,4000);return()=>clearInterval(id)},[status])
  async function act(id,a){await api('/api/approvals/'+id+'/'+a,{method:'POST',token});load()}
  return <><div className="page-head"><h2>{t.approvals}</h2><div className="actions"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t.all}</option><option value="pending">{t.pending}</option><option value="approved">{t.approved}</option><option value="rejected">{t.rejected}</option></select><button className="secondary" onClick={load}>{t.refresh}</button></div></div><div className="cards-list">{data.length?data.map(a=><div className="panel approval-card" key={a.id}><div><Badge value={a.status} t={t}/><h3>#{a.id} · {a.scan?.tool_name||a.scan?.source_type}</h3><p>{t.risk}: {a.scan?.risk_score}/100</p></div>{a.status==='pending'&&<div className="actions"><button className="primary" onClick={()=>act(a.id,'approve')}>{t.approve}</button><button className="danger-btn" onClick={()=>act(a.id,'reject')}>{t.reject}</button></div>}</div>):<div className="panel empty">{t.noApprovals}</div>}</div></>
}

function csv(v){return (v||[]).join(', ')}
function arr(v){return v.split(',').map(x=>x.trim()).filter(Boolean)}
function Policies({token,t}) {
  const [p,setP]=useState(null),[msg,setMsg]=useState(''); useEffect(()=>{api('/api/policies',{token}).then(setP)},[]); if(!p)return <div>{t.loading}</div>
  const toggle=c=>setP({...p,enabled_categories:p.enabled_categories.includes(c)?p.enabled_categories.filter(x=>x!==c):[...p.enabled_categories,c]})
  async function save(){await api('/api/policies',{method:'PUT',token,body:{approval_threshold:Number(p.approval_threshold),block_threshold:Number(p.block_threshold),llm_enabled:p.llm_enabled,require_approval_for_sensitive_files:p.require_approval_for_sensitive_files,enabled_categories:p.enabled_categories,blocked_domains:p.blocked_domains||[],blocked_tools:p.blocked_tools||[],approval_tools:p.approval_tools||[]}});setMsg('✓')}
  return <><div className="page-head"><h2>{t.policies}</h2></div><div className="panel settings"><div className="two-col"><label>{t.approvalThreshold}<input type="number" min="1" max="99" value={p.approval_threshold} onChange={e=>setP({...p,approval_threshold:e.target.value})}/></label><label>{t.blockThreshold}<input type="number" min="2" max="100" value={p.block_threshold} onChange={e=>setP({...p,block_threshold:e.target.value})}/></label></div><label className="toggle"><input type="checkbox" checked={p.llm_enabled} onChange={e=>setP({...p,llm_enabled:e.target.checked})}/>{t.llmEnabled}</label><label className="toggle"><input type="checkbox" checked={p.require_approval_for_sensitive_files} onChange={e=>setP({...p,require_approval_for_sensitive_files:e.target.checked})}/>{t.sensitiveApproval}</label><label>{t.blockedDomains}<input value={csv(p.blocked_domains)} onChange={e=>setP({...p,blocked_domains:arr(e.target.value)})}/><small>{t.blockedDomainsHelp}</small></label><label>{t.blockedTools}<input value={csv(p.blocked_tools)} onChange={e=>setP({...p,blocked_tools:arr(e.target.value)})}/><small>{t.blockedToolsHelp}</small></label><label>{t.approvalTools}<input value={csv(p.approval_tools)} onChange={e=>setP({...p,approval_tools:arr(e.target.value)})}/><small>{t.approvalToolsHelp}</small></label><h3>{t.categories}</h3><div className="chips">{p.available_categories.map(c=><button type="button" className={p.enabled_categories.includes(c)?'chip active':'chip'} onClick={()=>toggle(c)} key={c}>{c}</button>)}</div><button className="primary" onClick={save}>{t.save} {msg}</button></div></>
}

function Audit({token,t}) {const [data,setData]=useState([]),[eventType,setEventType]=useState('');const load=()=>api('/api/audit'+(eventType?'?event_type='+encodeURIComponent(eventType):''),{token}).then(setData);useEffect(()=>{load()},[eventType]);return <><div className="page-head"><h2>{t.audit}</h2><div className="actions"><input className="compact-input" placeholder={t.filterEvent} value={eventType} onChange={e=>setEventType(e.target.value)}/><button className="secondary" onClick={load}>{t.refresh}</button></div></div><section className="panel"><table><thead><tr><th>{t.event}</th><th>{t.details}</th><th>{t.date}</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.event_type}</td><td><code>{JSON.stringify(x.details)}</code></td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></section></>}

function Integration({token,t}) {
  const [status,setStatus]=useState(null),[newToken,setNewToken]=useState(''); const load=()=>api('/api/integrations/status',{token}).then(setStatus);useEffect(()=>{load()},[])
  async function generate(){const d=await api('/api/integrations/token/regenerate',{method:'POST',token});setNewToken(d.token);load()}
  return <><div className="page-head"><div><h2>{t.integrationTitle}</h2><p>{t.integrationText}</p></div></div><div className="split"><div className="panel"><h3>Status</h3>{status&&<><p>{t.codexStatus}: <b>{status.codex_token_configured?t.yes:t.no}</b></p><p>{t.ollamaStatus}: <b>{status.ollama_enabled?t.yes:t.no}</b></p><p>{t.postToolProtected}</p></>}<button className="primary" onClick={generate}>{t.generateToken}</button>{newToken&&<div className="token-box"><code>{newToken}</code><button onClick={()=>navigator.clipboard.writeText(newToken)}>{t.copy}</button><p>{t.tokenWarning}</p></div>}</div><div className="panel"><h3>{t.hookConfig}</h3><pre>{'$env:AGENT_GUARD_URL="http://127.0.0.1:8000"\n$env:AGENT_GUARD_TOKEN="ag_..."\n\n# '+t.installer+'\ncd codex\n.\\install_hooks.bat\n\n# Restart VS Code / Codex'}</pre></div></div></>
}

function LiveEvents({token,t}) {
  const [notice,setNotice]=useState(null)
  useEffect(()=>{if(!token)return;const base=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';const wsUrl=base.replace(/^http/,'ws')+'/api/ws?token='+encodeURIComponent(token);let ws;try{ws=new WebSocket(wsUrl);ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type!=='connected'){setNotice(d);setTimeout(()=>setNotice(null),5000)}}catch{}};ws.onopen=()=>ws.send('ping')}catch{}return()=>{try{ws?.close()}catch{}}},[token])
  if(!notice)return null
  return <div className="toast"><b>{t.liveAlert}</b><span>{notice.type}{notice.scan?` · ${notice.scan.decision} · ${notice.scan.risk_score}/100`:''}</span></div>
}

export default function App(){
  const [lang,setLang]=useState(localStorage.getItem('lang')||'en'),[token,setToken]=useState(localStorage.getItem('token')||''),[user,setUser]=useState(null),[page,setPage]=useState('dashboard');const t=useMemo(()=>translations[lang],[lang])
  useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('lang',lang)},[lang]);useEffect(()=>{if(token)api('/api/auth/me',{token}).then(setUser).catch(()=>{localStorage.removeItem('token');setToken('')})},[token])
  const onAuth=(tok,u)=>{localStorage.setItem('token',tok);setToken(tok);setUser(u)}, logout=()=>{localStorage.removeItem('token');setToken('');setUser(null)}
  if(!token)return <Auth lang={lang} setLang={setLang} onAuth={onAuth}/>
  const pages={dashboard:<Dashboard token={token} t={t}/>,projects:<Projects token={token} t={t}/>,scanner:<Scanner token={token} t={t} lang={lang}/>,approvals:<Approvals token={token} t={t}/>,policies:<Policies token={token} t={t}/>,audit:<Audit token={token} t={t}/>,integration:<Integration token={token} t={t}/>}
  return <div className="app-shell"><LiveEvents token={token} t={t}/><aside><div className="brand"><div className="brand-mark small">AG</div><div><b>{t.appName}</b><small>{t.tagline}</small></div></div><nav>{NAV.map(([id,icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><span>{icon}</span>{t[id]}</button>)}</nav><div className="aside-foot"><div className="user"><b>{user?.name}</b><small>{user?.email}</small></div><button className="secondary full" onClick={()=>setLang(lang==='en'?'ar':'en')}>{t.language}</button><button className="link full" onClick={logout}>{t.signOut}</button></div></aside><main>{pages[page]}</main></div>
}
